-- Users table
CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON users (email);

CREATE TABLE IF NOT EXISTS financial_data (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	date DATE NOT NULL,
	amount NUMERIC(19,2) NOT NULL,
	category VARCHAR(100) NOT NULL,
	description VARCHAR(500),
	type VARCHAR(50) NOT NULL,
	CONSTRAINT fk_financial_data_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_financial_data_user_date ON financial_data (user_id, date);
CREATE INDEX IF NOT EXISTS idx_financial_data_category ON financial_data (category);

CREATE TABLE IF NOT EXISTS forecasts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	forecast_date DATE NOT NULL,
	predicted_amount NUMERIC(19,2) NOT NULL,
	confidence_score NUMERIC(5,2) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_forecasts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_forecasts_user_date ON forecasts (user_id, forecast_date);


