-- Categories table
CREATE TABLE IF NOT EXISTS categories (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	type VARCHAR(50) NOT NULL,
	color VARCHAR(20),
	user_id BIGINT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_categories_user ON categories (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_categories_user_name ON categories (user_id, name);

-- User settings table
CREATE TABLE IF NOT EXISTS user_settings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	currency VARCHAR(10) NOT NULL DEFAULT 'USD',
	timezone VARCHAR(50) NOT NULL DEFAULT 'UTC',
	notification_preferences VARCHAR(255),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_settings_user ON user_settings (user_id);

