-- Add missing tables for JPA entities

-- Accounts table
CREATE TABLE IF NOT EXISTS accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	type VARCHAR(50) NOT NULL,
	balance NUMERIC(19,2) NOT NULL DEFAULT 0.00,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id BIGINT NOT NULL,
	CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_accounts_user ON accounts (user_id);

-- Budgets table (create before transactions to avoid FK reference issues)
CREATE TABLE IF NOT EXISTS budgets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	amount NUMERIC(19,2) NOT NULL,
	period VARCHAR(50) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id BIGINT NOT NULL,
	CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_budgets_user ON budgets (user_id);

-- Transactions table (create after budgets to allow FK reference)
CREATE TABLE IF NOT EXISTS transactions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	amount NUMERIC(19,2) NOT NULL,
	description VARCHAR(500),
	type VARCHAR(50) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	account_id BIGINT NOT NULL,
	budget_id BIGINT,
	CONSTRAINT fk_transactions_account FOREIGN KEY (account_id) REFERENCES accounts(id),
	CONSTRAINT fk_transactions_budget FOREIGN KEY (budget_id) REFERENCES budgets(id)
);

CREATE INDEX IF NOT EXISTS idx_transactions_account ON transactions (account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_budget ON transactions (budget_id);

-- Financial Goals table
CREATE TABLE IF NOT EXISTS financial_goals (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	target_amount NUMERIC(19,2) NOT NULL,
	current_amount NUMERIC(19,2) NOT NULL DEFAULT 0.00,
	target_date DATE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id BIGINT NOT NULL,
	CONSTRAINT fk_financial_goals_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_financial_goals_user ON financial_goals (user_id);
